language: node_js
node_js:
- '10'
cache: npm
before_script:
- npm install jest
- npm install react
- npm install jsdom
script: npm run test
deploy:
  provider: heroku
  api_key:
    secure: kQHs0e1YwXJjoEm2fLMIcBGj42ovX3obJZRr+nPks2JwnNHW8nLOlA+V/7G9SAILo9ulpjh+j47eioSRdj+VD/lQb/WhFzcLVbp/Yis3RdeeJ9Ljj3yx1VGmhK797lJz4Gyj/3j+7XXCog89pJ0LajJ7ph7YEARcM6wiloYxwV3UfQNhZaYHwpAYQL+/XDXaT33V7A5uF0tcuOm7St3oM2VIeQq0BLA8jGJHPzeu/arMIIOVihmhmOhHKuJEczeScOmk11604OQ/IQK90+6Wi4Hjh9CvaXq28AfHvIi6tkTyqQ63TSNoxe6dy0ZWk7M6CejpOzwMjb75zr2PJ8gS+ae6zK12yybzjyr49YawEBvu0eiyjpBy5iBcF8M4UKs3+CY4hrQlvB12754+ZXXSLttSefYfyPA29xfDzuUP3gXddhcwZaHlQ6/L0fKYleKkO9BYK4jrI9L6LWqZB3q+NuSKuxRWSd2BnvYIFXv6wMC5x07agKGJqxbDOLxma5ZuE/KCh+banzByOhDn3c0A5NtSA1xFEEsCVNk1aRgCegLW6YBJyrZw9CWAF6Xyv0jTHRYvLUGo8J5UewpaxoO3yfDnwuWavy6H94Pa181ICpqP7dGYQeYQdrl0aEPPk6yeS2UuWdQBkIA1PJkGnJr8G/G9/XbBYwCV2ISH8FfsSPI=
