language: node_js
node_js:
- '10'
cache: npm
before_script:
- npm i jest react jsdom
script: npm run test
deploy:
  provider: heroku
  app: stopwatch-reactive
  api_key:
    secure: ld3flHdSCpRR3+w3pVK6Rr6zDe6aeIrYALS1SHJnRLYZliQXMc/zgK8Ovhuwr4bsGbSce65B59FUJ5u1orbGlTC42jfUdseFgQoNXDI8M97+pZ1CbvlEPOJZpBFvBRhDYdPITXPSDICN9QsQbW97l3uhV6Mk5rJlu213U1NJONIgIRMiVlTxYi6IZe9Gd1vpClvASoVq+9x2Y3sZ0OyAFmDPAb3db0nnL75VWWOGdr5oz5I3HNHl8ueiIzH+6KNt1a+1s1k8LEIfT9U2+lQOiZV9wr5TDDJ+ZMJKAaCyl/jm05cOUtMm6T48eBpLnkprgedefHfz/H/FEo8ANsFKIj6fHaJgxB0axfLxeMwbGu3euv1yEeZ+HCx1xGA/0lIqsqO1OQe6gx9cYdYP+R5k6p9Lumi58MPYNLyJKpo20XJhA0b495nR3+g7/L+D+jwqej9fwW1W07SIVWOLNxIuieIbVBDHX1OUqii5mpzsxwzN3udHUfN6hkvVYpox5EuhsKF+u6BswlDG6eL1qs0dxQ9mosLCq2ZhtrTsNW9tX85Ku9rBj7ec4Eb0OkaGIpTuBhO+K7z16iYUGncApiCrm5ZlvIEzKA6ntiZP6ADkR/pgAG0VlAVNJ60zof+AMBq1uL9E5fyXRCCDbyLc+QT8n3wqEuonX6pDZd7+dnKE+F4=
  on:
    repo: Vboivin/reactiveStopwatch