language: node_js
node_js:
- '10'
cache: npm
before_script:
- npm i jest react jsdom
script: npm run test
deploy:
  provider: heroku
  app: stopwatch-reactive
  api_key:
    secure: Gp6rHSpIiicyLka1hUIvT90q9Kq30z6nBK6/+3nTOSC5K3zEHyQWFQ3T91wFFewdzc/u6CSQGhcR5pJ/4FPkK+D0IVAShcOIJoN2Pih98FchPy0/jRpWVBoQD0FcGnvEwxoTOpNlO0ksuRNAlX5jhvJI93ZccO7caxJOLn5Bx/f2A9W8/VIewFKRKCCEfQ5chXjOOHWmWijLsqKiJxZ8+BBnMEm3TmUW16gBxXROMoVSiJxq6pKGf27YOLklaJT2csLULp0X5fvSU14JXeSQHNSEUnwR/sNNtGmpxQQElu46eqZJ/y3Wwy2zajxwAmC0GFgU9GCUWJD3ExmX+WVxfzaCKeBMzi31WLfvjtv7No49D47g/Lpj926OxznNGSBDTcteL99+xSdMqbN13NDt2hxTM5L5tixYkPMNEpukqEGjgsgdAGG5d2hmFpAKvLsfFU0vDPfdxBqndFXxbuzu6aJf07UPOufztPdLnfRv0qz16iot2oJpL2cJtVhPt14SqIqhkRuaNTYykMjtz/e4RBfXG76qZ64ckSt7jMAKoRt2ZdqA6mwou41Ufucd5XQnCg1qEiof3rEC1IjL/moEN0tbIadx0kOL0uSEOCmEU0RdK3M9NHwfK44HRA3HHtmaIHMNDGoEkhb8auAFuKFhcNX1Ftrd2VeHtvonh/kecIg=
  on:
    repo: Vboivin/reactiveStopwatch
