language: node_js
node_js:
- '10'

before_script:
- npm i jest react jsdom
script: npm run tests

deploy:
  provider: s3
  access_key_id: AKIAIZGKEFT7V6FQSWCA
  secret_access_key:
    secure: ykbocjzP5utidpqA5jm/VZqRa9e3o0BK6SpqU2TfG9RmQS3rX7/qWlvD/K5Jpim1M/tN1999A3QzRFQs/gqADYuUxhIFB6y//e+Se7HnfvDgJodXMZ92xU0Irlf+rT2RQA66n1btrIpbZyFeiyDTwL9g2aqYNZVmDxo0B3oKKSF1/5UjVC9Rvob6d2gClJdaL/TpErjvdpASkpMof3tzLu6rwMr0yZYS2FXXgg6VGSKDsQupvV7z7QtdJLIulBTM34BnHZrECOsMNjl6Uw8eh1uaJ3iUmN7WZTJkNawkejrBxXQtmpidcJn9k/49vFKheq1fN8OQe/uIuf0y9YOZ6i/JhXAr1/nH+/jX+Q2IIzO7dPNqWjdFhpHzcTclzHzdFrmPOBIgMpfGNI4PWC5RA6z+9Nnww3azi54kh2a1XrV7F2Q2guZxHeqt9Tf4dCDgoK6HUYsOV7q5t6F1G3Vq+6SQ5aqfoiJiJd4V4Pv/S9mWZsvWC0frbeumzVZngM7Z3P2XjiUeGz18VSfYFI+LZ2Hh2VZCovn4dkjRXnQCmEgfYSXMauY/zPiP8s2l6QVx6ZHE6G6JraUZnAo7tivtOS31sZqnOyW33OA/2coTdxEM7tWVu5i/lLIidP2LLQ5BqJFZmVHjfNYIgzR9cZpIr+F7PCu/hvKESqXmX+feeCc=
  bucket: reactive-stopwatch
  local-dir: dist
  acl: public_read
  on:
    repo: qiqi0725/reactiveStopwatch
  region: us-east-2
  default_text_charset: 'utf-8'
